---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    namespace: default
  tasks:
  #- name: check if kubeconfig file exists
  #  stat: 
  #    path: "{{ ansible_env.HOME }}/.kube/config"
  #  register: kube_conf

  - name: Check service account has imagePullSecret
    command: kubectl get serviceaccounts default -o yaml -n {{ namespace }}
    register: cmd_result

  - name: print debug message
    debug:
      msg="{{ cmd_result }}"

  - name: Check Image Pull Secret exists
    debug: 
      msg: "imagePullSecrets not found"
    when: cmd_result.stdout.find('imagePullSecrets:') == -1
